import type { ModuleId } from "./brand.js";

/**
 * Valores padrao de cada modulo.
 *
 * Estas chaves sao o contrato entre dashboard e bot. O dashboard grava
 * apenas o que o cliente mudou; o bot sempre le o config resolvido, que e
 * o padrao + a config do grupo + a excecao do servidor.
 */
export const moduleDefaults: Record<ModuleId, Record<string, unknown>> = {
  servers: {
    syncEveryMinutes: 60,
    syncRoles: true,
    syncChannels: true,
    announceJoinChannelId: "",
    announceLeaveChannelId: "",
    nicknameOnJoin: false,
    joinMessage: "Bem-vindo(a) ao servidor, {user}!",
    leaveMessage: "{user} saiu do servidor.",
    maintenanceMode: false,
    maintenanceMessage: "O servidor está em manutenção. Volte mais tarde."
  },
  statistics: {
    retentionDays: 180,
    trackMessages: true,
    trackVoice: false,
    trackJoins: true,
    trackTickets: true,
    anonymizeUsers: true,
    digestChannelId: "",
    digestHourUtc: 12,
    exportFormat: "json",
    highlightTopMembers: 5,
    trackReactions: false,
    trackCommands: true
  },
  staff: {
    staffRoleIds: [],
    logChannelId: "",
    performanceWindowDays: 30,
    requireReason: true,
    inactivityDays: 14,
    pingOnClaim: true,
    shiftLogChannelId: "",
    autoArchiveDays: 7,
    escalationRoleId: "",
    maxConcurrentTickets: 5,
    responseTimeGoalMinutes: 30
  },
  roles: {
    allowAiDrafts: true,
    protectedRoleIds: [],
    syncNames: true,
    autoRemoveOnLeave: false,
    mentionableByDefault: false,
    hoistNewRoles: false,
    maxRolesPerMember: 25,
    autoSyncIntervalHours: 24,
    hierarchyLimit: 10,
    defaultRoleIds: []
  },
  automations: {
    requireApprovalForDestructiveActions: true,
    logChannelId: "",
    dryRun: false,
    maxActionsPerHour: 30,
    allowChannelCreate: false,
    allowRoleAssign: true,
    notifyChannelId: "",
    retryOnFailure: true,
    maxRetries: 3,
    cooldownSeconds: 5,
    allowSendMessage: true,
    allowNicknameChange: false
  },
  integrations: {
    webhookAllowlist: [],
    signingSecretConfigured: false,
    allowIncoming: false,
    timeoutMs: 4000,
    retryCount: 2,
    includeGuildId: true,
    rateLimitPerMinute: 60,
    healthCheckIntervalMinutes: 5,
    logPayloads: false,
    customHeaders: []
  },
  moderation: {
    logChannelId: "",
    staffRoleIds: [],
    defaultTimeoutMinutes: 60,
    escalateAfterStrikes: 3,
    banDeleteDays: 1,
    dmOnPunish: true,
    requireEvidence: false,
    appealChannelId: "",
    autoUnmuteAfterTimeout: true,
    strikeExpiryDays: 30,
    publicLogging: false,
    pardonsEnabled: true,
    maxStrikesBeforeBan: 5
  },
  automod: {
    logChannelId: "",
    messageLimit: 6,
    windowSeconds: 10,
    duplicateLimit: 3,
    blockInvites: true,
    action: "delete",
    timeoutMinutes: 10,
    blockedTerms: [],
    blockedDomains: [],
    ignoredChannelIds: [],
    ignoredRoleIds: [],
    mentionLimit: 8,
    scanImages: true,
    warnMessage: "Sua mensagem foi removida pelo filtro automático.",
    blockLinks: false,
    allowedDomains: [],
    capsThresholdPercent: 70,
    minLength: 0,
    maxLength: 0,
    antiGhostPing: true
  },
  security: {
    alertChannelId: "",
    raidJoinThreshold: 12,
    raidWindowSeconds: 60,
    nukeActionThreshold: 5,
    nukeWindowSeconds: 30,
    response: "lockdown_review",
    timeoutMinutes: 60,
    trustedRoleIds: [],
    minAccountAgeHours: 24,
    quarantineNewMembers: false,
    alertStaffRoleIds: [],
    raidMode: "smart",
    autoBanRepeatOffenders: false,
    whitelistRoleIds: [],
    alertOnMassBan: true,
    alertOnMassChannelDelete: true,
    lockdownMessage: "O servidor está em modo de proteção. Aguarde a equipe resolver."
  },
  logs: {
    channelId: "",
    retentionDays: 180,
    logModeration: true,
    logMembers: true,
    logMessages: false,
    logVoice: false,
    logRoles: true,
    logChannels: true,
    logBans: true,
    ignoreBotMessages: true,
    ignoreChannelIds: [],
    logThreadEvents: true,
    logStageEvents: true,
    logScheduledEvents: true,
    logAutoMod: true,
    compactMode: false,
    includeTimestamp: true,
    mentionOnCritical: false,
    mentionRoleId: ""
  },
  tickets: {
    panelChannelId: "",
    categoryId: "",
    staffRoleIds: [],
    transcriptChannelId: "",
    logChannelId: "",
    aiSupportEnabled: true,
    closeAfterHours: 48,
    panelFormat: "components_v2",
    panelTitle: "Central de atendimento",
    panelDescription: "Abra um atendimento privado e fale com a equipe.",
    panelAccentColor: "#7c5cff",
    feedbackEnabled: true,
    maxOpenPerUser: 1,
    pingStaffOnOpen: true,
    namingPattern: "atendimento-{user}",
    welcomeMessage: "Olá! Descreva o que você precisa. A equipe já foi notificada.",
    autoCloseInactiveHours: 24,
    reopenEnabled: true,
    satisfactionSurvey: true,
    priorityEnabled: true,
    tags: [],
    slaWarningMinutes: 60,
    escalationRoleId: ""
  },
  forms: {
    reviewerRoleIds: [],
    reviewChannelId: "",
    useAiPreReview: false,
    panelFormat: "components_v2",
    panelTitle: "Candidaturas",
    panelDescription: "Envie sua candidatura pelo formulario seguro.",
    panelAccentColor: "#7c5cff",
    cooldownHours: 24,
    minAccountAgeDays: 0,
    notifyReviewers: true,
    autoRejectAfterDays: 14,
    requireReasonOnReject: true,
    anonymousSubmissions: false,
    maxSubmissionsPerUser: 3,
    archiveApprovedAfterDays: 90
  },
  knowledge: {
    answerChannelId: "",
    useAi: true,
    requireApprovedArticles: true,
    mentionRequired: false,
    minQuestionLength: 12,
    cooldownSeconds: 20,
    preferFastModel: true,
    fallbackMessage: "",
    maxArticlesPerSearch: 5,
    similarityThreshold: 0.6,
    autoSuggest: true,
    suggestInAllChannels: false,
    includeArticleLink: true,
    logSearches: false,
    logChannelId: ""
  },
  ocr: {
    provider: "hybrid",
    language: "pt",
    model: "qwen/qwen3.8-27b",
    retainExtractedText: false,
    maxImageMb: 8,
    reviewChannelId: "",
    confidenceThreshold: 0.7,
    cacheResults: true,
    cacheTtlMinutes: 60,
    autoDeleteSuspicious: false,
    logChannelId: ""
  }
};

export function defaultsFor(module: ModuleId): Record<string, unknown> {
  return { ...(moduleDefaults[module] ?? {}) };
}
