/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppFormsRouteImport } from './routes/app/forms'
import { Route as AppKnowledgeRouteImport } from './routes/app/knowledge'
import { Route as AppLogsRouteImport } from './routes/app/logs'
import { Route as AppModerationRouteImport } from './routes/app/moderation'
import { Route as AppProtectRouteImport } from './routes/app/protect'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppStaffRouteImport } from './routes/app/staff'
import { Route as AppStatsRouteImport } from './routes/app/stats'
import { Route as AppTicketsRouteImport } from './routes/app/tickets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsRoute = AppFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppModerationRoute = AppModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AppRoute,
} as any)
const AppProtectRoute = AppProtectRouteImport.update({
  id: '/protect',
  path: '/protect',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/app/forms': typeof AppFormsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/logs': typeof AppLogsRoute
  '/app/moderation': typeof AppModerationRoute
  '/app/protect': typeof AppProtectRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/stats': typeof AppStatsRoute
  '/app/tickets': typeof AppTicketsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app/forms': typeof AppFormsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/logs': typeof AppLogsRoute
  '/app/moderation': typeof AppModerationRoute
  '/app/protect': typeof AppProtectRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/stats': typeof AppStatsRoute
  '/app/tickets': typeof AppTicketsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/app/forms': typeof AppFormsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/logs': typeof AppLogsRoute
  '/app/moderation': typeof AppModerationRoute
  '/app/protect': typeof AppProtectRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/stats': typeof AppStatsRoute
  '/app/tickets': typeof AppTicketsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/app/forms'
    | '/app/knowledge'
    | '/app/logs'
    | '/app/moderation'
    | '/app/protect'
    | '/app/settings'
    | '/app/staff'
    | '/app/stats'
    | '/app/tickets'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app/forms'
    | '/app/knowledge'
    | '/app/logs'
    | '/app/moderation'
    | '/app/protect'
    | '/app/settings'
    | '/app/staff'
    | '/app/stats'
    | '/app/tickets'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/app/forms'
    | '/app/knowledge'
    | '/app/logs'
    | '/app/moderation'
    | '/app/protect'
    | '/app/settings'
    | '/app/staff'
    | '/app/stats'
    | '/app/tickets'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forms': {
      id: '/app/forms'
      path: '/forms'
      fullPath: '/app/forms'
      preLoaderRoute: typeof AppFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logs': {
      id: '/app/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/moderation': {
      id: '/app/moderation'
      path: '/moderation'
      fullPath: '/app/moderation'
      preLoaderRoute: typeof AppModerationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/protect': {
      id: '/app/protect'
      path: '/protect'
      fullPath: '/app/protect'
      preLoaderRoute: typeof AppProtectRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/staff': {
      id: '/app/staff'
      path: '/staff'
      fullPath: '/app/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stats': {
      id: '/app/stats'
      path: '/stats'
      fullPath: '/app/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tickets': {
      id: '/app/tickets'
      path: '/tickets'
      fullPath: '/app/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFormsRoute: typeof AppFormsRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppLogsRoute: typeof AppLogsRoute
  AppModerationRoute: typeof AppModerationRoute
  AppProtectRoute: typeof AppProtectRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppStatsRoute: typeof AppStatsRoute
  AppTicketsRoute: typeof AppTicketsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFormsRoute: AppFormsRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppLogsRoute: AppLogsRoute,
  AppModerationRoute: AppModerationRoute,
  AppProtectRoute: AppProtectRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
  AppStatsRoute: AppStatsRoute,
  AppTicketsRoute: AppTicketsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
